# Blimp Names #

# Catching
catching_blimp_names:
  - BurnCream
  - SillyAh
  - Turbo
  - GameChamber
  - GravyLongWay
  - SuperBeef

# Attacking
attacking_blimp_names:
  - Yoshi
  - Luigi
  - Geoph
  - ThisGuy
